# Generated by Django 5.1.4 on 2024-12-16 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="messages", to="messenger.tag"
            ),
        ),
    ]
