# Generated by Django 5.1.4 on 2024-12-16 08:10

from django.db import migrations, models

import messenger.utils


class Migration(migrations.Migration):

    dependencies = [
        ("messenger", "0002_message_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=messenger.utils.message_image_file_path
            ),
        ),
    ]
